steps:
# Step 1: Build the container image
- name: 'gcr.io/cloud-builders/docker'
  args:
    - 'build'
    - '-t'
    - '${_REGION}-docker.pkg.dev/$PROJECT_ID/${_AR_REPO_NAME}/${_SERVICE_NAME}:${COMMIT_SHA:-latest}'
    - '.'
  id: 'Build Docker Image'

# Step 2: Push the container image to Artifact Registry
- name: 'gcr.io/cloud-builders/docker'
  args:
    - 'push'
    - '${_REGION}-docker.pkg.dev/$PROJECT_ID/${_AR_REPO_NAME}/${_SERVICE_NAME}:${COMMIT_SHA:-latest}'
  id: 'Push to Artifact Registry'
  waitFor: ['Build Docker Image'] # Ensures build is complete before pushing

# Step 3: Deploy to Cloud Functions (2nd Gen)
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: 'gcloud'
  args:
    - 'functions'
    - 'deploy'
    - '${_SERVICE_NAME}' # Function name
    - '--gen2'
    - '--region=${_REGION}'
    - '--docker-image=${_REGION}-docker.pkg.dev/$PROJECT_ID/${_AR_REPO_NAME}/${_SERVICE_NAME}:${COMMIT_SHA:-latest}'
    - '--trigger-http'
    - '--allow-unauthenticated' # Review and adjust as per your authentication needs
    - '--memory=${_MEMORY}'
    - '--timeout=${_TIMEOUT}' # Max 3600s for HTTP-triggered 2nd gen functions
    - '--max-instances=${_MAX_INSTANCES}'
    - '--concurrency=${_CONCURRENCY}'
    # Note: CPU for Cloud Functions (2nd gen) is allocated based on memory.
    # For 2Gi memory, it typically gets 1 vCPU.
    # The PLATFORM (linux/amd64) from .env.deploy is the default.
    # Optional: --service-account=YOUR_FUNCTION_RUNTIME_SERVICE_ACCOUNT_EMAIL
  id: 'Deploy to Cloud Functions'
  waitFor: ['Push to Artifact Registry'] # Ensures image is pushed before deploying

# This specifies the image created by the build, which can be used by other parts of the build (e.g., for vulnerability scanning)
images:
  - '${_REGION}-docker.pkg.dev/$PROJECT_ID/${_AR_REPO_NAME}/${_SERVICE_NAME}:${COMMIT_SHA:-latest}'

substitutions:
  _SERVICE_NAME: 'seeker-podcast-processor' # From .env.deploy SERVICE_NAME
  _REGION: 'us-central1'                   # From .env.deploy REGION
  _MEMORY: '2Gi'                           # From .env.deploy MEMORY
  _TIMEOUT: '3600s'                        # From .env.deploy TIMEOUT (converted to seconds)
  _MAX_INSTANCES: '5'                      # From .env.deploy MAX_INSTANCES
  _CONCURRENCY: '1000'                     # From .env.deploy CONCURRENCY
  _AR_REPO_NAME: 'seeker-functions-repo'   # IMPORTANT: You need to create this Docker repository in Artifact Registry

# PROJECT_ID and COMMIT_SHA are built-in substitutions provided by Cloud Build.
# $PROJECT_ID will be automatically replaced with 'metapod-d52fc' from your .env.deploy.

options:
  logging: CLOUD_LOGGING_ONLY
